### ISSUE TITLE
"Theme konfigurieren"-Variablen als Variablen im Frontend verfügbar machen

### ISSUE THREAD

**Issue by heimseiten** [contao-thememanager/core#7]
Erstmal vielen Dank für die tolle Erweiterung. Bzw. Eure vielen tollen Erweiterungen ;).

Es wäre sehr komfortabel, wenn die Variablen, welche mit "Theme konfigurieren" gefüllt werden können, irgendwie im Frontend zur Verfügung stehen würden. Entweder durch eine bspw. _variables.scss, die neben die Datei _theme.css gelegt werden könnte. Oder durch eine variables.css mit nativen css-Variablen.

Ich gehe nicht davon aus, dass Euch diese Funktionalität besonders hilfreich wäre und bin mir bewusst, dass damit die Chancen der Umsetzung dieses Tickets gegen Null gehen. Trotzdem wollte ich mal höflich nachfragen.

Liebe Grüße aus der erweiterten Nachbarschaft
(Bitte entschuldigt diesen unkonventionellen Tickettext ;))

**Comment by zoglo** [comment]
Hallo @heimseiten ,

vielen Dank für dein Feedback. Bezüglich deiner Problematik muss ich dein Problem noch weiter erörtern.


### Geht es hierbei nur um die SCSS-Variablen?

Sofern du nur die eingestellten Variablen der Konfiguration für dein scss brauchst (z.B. $primary oder $text-color-regular), greift der interne Theme-Compiler (Layout -> Themes -> Theme bearbeiten -> Theme-Compiler) schon darauf zu.



### Fehlen dir Custom Properties (--* / CSS Variablen)?

Geht es dir darum, dass dir die Theme-Variablen welche du in der ThemeManagerConfig eingestellt hast, auch als **CSS Variablen** zur Verfügung stehen, damit du dein eigenes CSS so schreiben kannst:

```scss
:root {
  --color-primary: $primary;
  --color-secondary: $secondary;
}


.button .design-primary {
  background-color: var(--color-primary);
}

.bg-secondary {
  background-color: var(--color-secondary);
}
```

### Oder ist hier sogar gewünscht, dass das komplette Framework und seine Komponenten über CSS-Variablen laufen?

Grundsätzlich ist es jetzt schon möglich anstatt einer Farbe auch eine weitere CSS Variable einzutragen:

#### Ein Beispiel
Das Feld $h1-color-invert in der ThemeManagerConfig  kann sowohl **$text-color-invert**, als auch **var(--color-text-invert)** beinhalten.

Im ersten Fall würde beim Kompilieren die Variable genutzt werden, im zweiten Fall wird der Wert einfach reingeschrieben und kann somit weiterverwendet werden.



#### Konfiguration
Um dir auch jetzt schon die Custom Properties auf den :root zur Verfügung zu stellen, müsstest du lediglich eine SCSS-Stylesheet anlegen, diese über den Theme-Compiler (wie oben erwähnt) als Skin-Quelldatei mitgeben und kompilieren. Die kompilierte Stylesheet kannst du somit in deinen Layout-Einstellungen einbinden.

#### Eine _root.scss könnte wie folgt aussehen:

```scss
:root {
  --body-bg: $body-bg;

  --color-primary: $primary;
  --color-secondary: $secondary;
  --color-light: $light;
  --color-dark: $dark;

  --color-text-regular: $text-color-regular;
  --color-text-invert: $text-color-invert;

  --font-size-base: $font-size-base;
  
  --font-weight-base: $font-weight-base;
  --font-weight-light:  $font-weight-light;
  --font-weight-regular:  $font-weight-regular;
  --font-weight-medium: $font-weight-medium;
  --font-weight-semibold: $font-weight-semibold;
  --font-weight-bold: $font-weight-bold;
}
```

Diese CSS-Variablen müsstest du dann in der ThemeManagerConfig für deine gewünschten Komponenten eintragen (wie z.B. : **$h1-color-invert: var(--color-text-invert)**)


### In Zukunft

Grundsätzlich haben wir die Verwendung von Custom Properties schon besprochen, diese sollten jedoch in Ihrer Verwendung limitiert sein, da nicht nur unser grid-layout, aber auch viele andere Komponenten über Mixins und Funktionen gestyled und berechnet werden. 

Wenn man **alle** Variablen in Custom Properties umschreibt, müsste die Berechnung Client-seitig über calc(), filter o.ä. passieren und somit die Performance der Webseiten beeinträchtigen.

Gewisse Variablen als Custom Properties zur Verfügung zu stellen, sollte kein Problem sein und macht in Zukunft auch Sinn, da damit auch Dark-Mode besser supportet werden kann.
